server:
  port: 8080

spring:
  application:
    name: forum

  datasource:
    url: jdbc:postgresql://localhost:5433/forum
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true