server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APP_NAME:forum}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/forum}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}